import json
import os
import re
from collections import Counter
from datetime import date

from dotenv import load_dotenv
from flask import Flask, jsonify, render_template, request
from groq import Groq
from supabase import Client, create_client

# Load serverless workspace variables.
load_dotenv()

app = Flask(__name__, template_folder='../templates')

# Supabase Client Initialization
SUPABASE_URL = os.environ.get("SUPABASE_URL", "")
SUPABASE_ANON_KEY = os.environ.get("SUPABASE_ANON_KEY", "")
GROQ_MODEL = os.environ.get("GROQ_MODEL", "llama-3.3-70b-versatile")
AI_MEDICAL_DISCLAIMER = (
    "This summary is generated by AI from user-entered information. It is not a medical diagnosis, "
    "does not replace an examination by a licensed clinician, and should be verified before acting on it."
)

supabase_client: Client | None = None
if SUPABASE_URL and SUPABASE_ANON_KEY and "your-supabase" not in SUPABASE_URL:
    try:
        supabase_client = create_client(SUPABASE_URL, SUPABASE_ANON_KEY)
    except Exception as e:
        print(f"Supabase client initialization warning: {e}")


@app.route('/')
def home():
    """Renders the main health summary console interface."""
    return render_template(
        'index.html',
        supabase_url=SUPABASE_URL,
        supabase_anon_key=SUPABASE_ANON_KEY
    )


def safe_text(value, default="Not provided", max_length=4000):
    """Converts user-provided values into bounded plain text for prompt construction."""
    if value is None:
        return default

    text = str(value).strip()
    if not text:
        return default

    return text[:max_length]


def safe_int(value, default=0, minimum=None, maximum=None):
    """Safely converts values to integers and optionally clamps the result."""
    try:
        parsed = int(value)
    except (TypeError, ValueError):
        parsed = default

    if minimum is not None:
        parsed = max(minimum, parsed)
    if maximum is not None:
        parsed = min(maximum, parsed)

    return parsed


def calculate_age(birthday):
    """Returns a best-effort age string from an ISO date without failing the request."""
    if not birthday or birthday == "Not provided":
        return "Not provided"

    try:
        born = date.fromisoformat(birthday)
        today = date.today()
        age = today.year - born.year - ((today.month, today.day) < (born.month, born.day))
        return str(max(age, 0))
    except (TypeError, ValueError):
        return "Not provided"


def normalize_profile(user_profile):
    """Normalizes the profile object into the fields used by synthesis and chat."""
    user_profile = user_profile if isinstance(user_profile, dict) else {}

    first_name = safe_text(user_profile.get('firstName'), default="", max_length=100)
    last_name = safe_text(user_profile.get('lastName'), default="", max_length=100)
    full_name = f"{first_name} {last_name}".strip() or "Patient (Unspecified)"
    birthday = safe_text(user_profile.get('birthday'), max_length=30)

    return {
        "first_name": first_name,
        "last_name": last_name,
        "full_name": full_name,
        "birthday": birthday,
        "age": calculate_age(birthday),
        "height": safe_text(user_profile.get('height'), max_length=100),
        "weight": safe_text(user_profile.get('weight'), max_length=100),
        "gender": safe_text(user_profile.get('gender'), max_length=100),
        "medical_notes": safe_text(
            user_profile.get('medicalNotes'),
            default="None reported",
            max_length=4000
        )
    }


def build_profile_text_block(profile):
    """Formats normalized patient information for the language model."""
    return (
        f"Patient Name: {profile['full_name']}\n"
        f"Date of Birth: {profile['birthday']}\n"
        f"Approximate Age: {profile['age']}\n"
        f"Biological Sex / Gender: {profile['gender']}\n"
        f"Height: {profile['height']} | Weight: {profile['weight']}\n"
        f"Pre-existing Medical History / Notes: {profile['medical_notes']}"
    )


def build_timeline_payload(timeline_logs):
    """Converts the calendar dictionary into a stable, chronological list."""
    timeline_payload = []

    for date_key in sorted(timeline_logs.keys()):
        raw_entry = timeline_logs.get(date_key, {})
        entry = raw_entry if isinstance(raw_entry, dict) else {}
        raw_symptoms = entry.get("symptoms", [])
        symptoms = raw_symptoms if isinstance(raw_symptoms, list) else []

        timeline_payload.append({
            "date": safe_text(date_key, default="Unknown date", max_length=30),
            "pain_severity_scale_1_to_10": safe_int(
                entry.get("severity", 0),
                default=0,
                minimum=0,
                maximum=10
            ),
            "symptoms_reported": [safe_text(symptom, max_length=100) for symptom in symptoms[:20]],
            "patient_notes": safe_text(entry.get("notes"), default="", max_length=2000)
        })

    return timeline_payload


def calculate_timeline_statistics(timeline_payload):
    """Builds objective counts used by both the AI and deterministic fallback."""
    severity_values = [entry["pain_severity_scale_1_to_10"] for entry in timeline_payload]
    high_severity_days = [
        entry["date"]
        for entry in timeline_payload
        if entry["pain_severity_scale_1_to_10"] >= 7
    ]

    symptom_counter = Counter()
    all_notes = []

    for entry in timeline_payload:
        for symptom in entry["symptoms_reported"]:
            normalized_symptom = symptom.strip().lower()
            if normalized_symptom:
                symptom_counter[normalized_symptom] += 1

        if entry["patient_notes"]:
            all_notes.append(entry["patient_notes"].lower())

    total_days = len(timeline_payload)
    average_severity = round(sum(severity_values) / total_days, 1) if total_days else 0.0

    return {
        "total_days": total_days,
        "average_severity": average_severity,
        "peak_severity": max(severity_values) if severity_values else 0,
        "high_severity_days": high_severity_days,
        "high_severity_count": len(high_severity_days),
        "symptom_counter": symptom_counter,
        "most_common_symptoms": symptom_counter.most_common(5),
        "combined_notes": " ".join(all_notes)
    }


def determine_recommended_doctors(timeline_logs):
    """Analyzes logged symptoms and notes to suggest relevant specialists in plain terms."""
    all_symptoms = set()
    all_notes = ""

    for entry in timeline_logs.values():
        if not isinstance(entry, dict):
            continue

        syms = entry.get('symptoms', [])
        if isinstance(syms, list):
            for symptom in syms:
                all_symptoms.add(str(symptom).lower())

        note = entry.get('notes', '')
        if note:
            all_notes += " " + str(note).lower()

    doctors = []

    # Check for Neurological symptoms.
    if any(s in all_symptoms for s in ['migraine', 'brain fog', 'headache']) or 'headache' in all_notes or 'dizzy' in all_notes:
        doctors.append({
            "title": "Neurologist",
            "subtitle": "Brain & Nerve Specialist",
            "description": "A neurologist is a specialist who treats conditions affecting the brain, spine, and nerves. They can help diagnose and manage severe headaches, migraines, memory issues, and nervous system flare-ups."
        })

    # Check for Rheumatology / Joint symptoms.
    if any(s in all_symptoms for s in ['joint pain', 'fatigue']) or 'joint' in all_notes or 'stiff' in all_notes or 'arthritis' in all_notes:
        doctors.append({
            "title": "Rheumatologist",
            "subtitle": "Joint & Autoimmune Specialist",
            "description": "A rheumatologist specializes in joint, muscle, and bone diseases as well as autoimmune conditions. They help manage chronic swelling, stiffness, fatigue, and pain throughout the body."
        })

    # Check for Gastroenterology symptoms.
    if any(s in all_symptoms for s in ['nausea', 'stomach pain']) or 'stomach' in all_notes or 'gut' in all_notes or 'nausea' in all_notes:
        doctors.append({
            "title": "Gastroenterologist",
            "subtitle": "Digestive Health Specialist",
            "description": "A gastroenterologist focuses on digestive health, including the stomach, intestines, and gut. They help evaluate and treat ongoing stomach pain, nausea, bloating, or digestive discomfort."
        })

    # Check for Sleep Specialist symptoms.
    if 'insomnia' in all_symptoms or 'sleep' in all_notes or 'exhausted' in all_notes:
        doctors.append({
            "title": "Sleep Specialist",
            "subtitle": "Rest & Sleep Expert",
            "description": "A sleep specialist evaluates sleep disorders like chronic insomnia, sleep apnea, or daytime fatigue. They help you find strategies to improve sleep quality and body recovery."
        })

    # Check for Mental Health / Anxiety.
    if 'anxiety' in all_symptoms or 'stress' in all_notes or 'anxious' in all_notes:
        doctors.append({
            "title": "Psychiatrist or Therapist",
            "subtitle": "Mental & Behavioral Health Specialist",
            "description": "A mental health specialist helps you manage stress, anxiety, mood changes, and the emotional impact of living with chronic symptoms."
        })

    # Primary Care Physician is always included as the foundational doctor.
    doctors.append({
        "title": "Primary Care Physician (PCP)",
        "subtitle": "General Health Doctor",
        "description": "Your primary doctor is your main healthcare partner who looks at your total health picture, performs initial checkups, and coordinates specialized medical care."
    })

    # Return the first three unique recommendations.
    unique_doctors = []
    seen_titles = set()
    for doctor in doctors:
        if doctor["title"] not in seen_titles:
            unique_doctors.append(doctor)
            seen_titles.add(doctor["title"])

    return unique_doctors[:3]


def select_fallback_possibilities(statistics):
    """Selects cautious, non-diagnostic possibility labels for fallback output."""
    symptoms = set(statistics["symptom_counter"].keys())
    notes = statistics["combined_notes"]

    minor_label = "Temporary lifestyle, sleep, hydration, stress, or routine-related symptom flare"
    medium_label = "Persistent symptom pattern that should be reviewed by a primary-care clinician"
    major_label = "Less common medical condition that cannot be excluded without an in-person evaluation"

    if symptoms.intersection({'headache', 'migraine', 'brain fog'}) or 'dizzy' in notes:
        medium_label = "Recurring headache or migraine-spectrum pattern"
        major_label = "Neurologic or vascular condition requiring prompt assessment if warning signs are present"
    elif symptoms.intersection({'nausea', 'stomach pain'}) or any(term in notes for term in ['stomach', 'gut', 'bloating']):
        medium_label = "Recurring digestive irritation or functional gastrointestinal pattern"
        major_label = "Inflammatory, obstructive, bleeding, or other digestive condition requiring medical evaluation"
    elif 'joint pain' in symptoms or any(term in notes for term in ['joint', 'stiff', 'swelling']):
        medium_label = "Muscle, joint, overuse, or inflammatory pain pattern"
        major_label = "Systemic inflammatory or neurologic condition requiring clinician assessment"
    elif symptoms.intersection({'insomnia', 'anxiety', 'fatigue'}):
        medium_label = "Sleep and stress-related symptom amplification"
        major_label = "Underlying medical, sleep, or mental-health condition contributing to persistent symptoms"

    high_day_ratio = (
        statistics["high_severity_count"] / statistics["total_days"]
        if statistics["total_days"]
        else 0
    )

    major_probability = max(10, min(25, round(10 + high_day_ratio * 20)))
    medium_probability = max(25, min(45, round(30 + high_day_ratio * 15)))
    minor_probability = 100 - medium_probability - major_probability

    if minor_probability < 30:
        difference = 30 - minor_probability
        minor_probability = 30
        medium_probability = max(20, medium_probability - difference)

    return {
        "minor": {
            "label": minor_label,
            "probability": minor_probability
        },
        "medium": {
            "label": medium_label,
            "probability": medium_probability
        },
        "major": {
            "label": major_label,
            "probability": major_probability
        }
    }


def format_symptom_frequency(statistics):
    """Formats the most common symptom counts for display."""
    if not statistics["most_common_symptoms"]:
        return "No named symptoms were selected; the summary relies mainly on severity and notes."

    return ", ".join(
        f"{symptom.title()} ({count} day{'s' if count != 1 else ''})"
        for symptom, count in statistics["most_common_symptoms"]
    )


def generate_fallback_synthesis(profile, statistics):
    """Generates a detailed safe Markdown brief when the AI API key is unconfigured."""
    possibilities = select_fallback_possibilities(statistics)
    symptom_frequency = format_symptom_frequency(statistics)
    high_dates = ", ".join(statistics["high_severity_days"][:8]) or "None recorded"

    return f"""### IMPORTANT AI SAFETY NOTICE
* {AI_MEDICAL_DISCLAIMER}
* The percentages below are rough educational estimates generated from incomplete self-reported data. They are not validated medical probabilities.

### 1. PERSONAL INFORMATION
* **Name**: {profile['full_name']}
* **Date of Birth / Approximate Age**: {profile['birthday']} / {profile['age']}
* **Gender**: {profile['gender']}
* **Height / Weight**: {profile['height']} / {profile['weight']}
* **Medical Background Provided**: {profile['medical_notes']}

### 2. WHAT YOUR LOGS SHOW
* **Tracking Coverage**: {statistics['total_days']} logged day(s)
* **Average / Highest Pain Level**: {statistics['average_severity']} / 10 average; {statistics['peak_severity']} / 10 highest
* **High-Pain Days (7+)**: {statistics['high_severity_count']} day(s): {high_dates}
* **Most Frequent Symptoms**: {symptom_frequency}

### 3. MINOR / LOWER-CONCERN POSSIBILITY — {possibilities['minor']['probability']}%
* **Possible Explanation**: {possibilities['minor']['label']}.
* **Why It May Fit**: Short-lived symptom changes commonly vary with sleep, hydration, stress, meals, exertion, and routine. Your entries do not provide an examination, vital signs, or laboratory data to confirm a cause.
* **What Is Missing**: Duration of each episode, medication history, vital signs, physical examination findings, and relevant laboratory or imaging results.

### 4. MEDIUM / MODERATE-CONCERN POSSIBILITY — {possibilities['medium']['probability']}%
* **Possible Explanation**: {possibilities['medium']['label']}.
* **Why It May Fit**: Repeated symptoms across multiple logged days can indicate a recurring pattern rather than one isolated event. A clinician can compare timing, triggers, associated symptoms, and examination findings.
* **What Is Missing**: A clinician interview, physical examination, and targeted testing needed to distinguish common causes from conditions needing treatment.

### 5. MAJOR / HIGHER-CONCERN POSSIBILITY — {possibilities['major']['probability']}%
* **Possible Explanation**: {possibilities['major']['label']}.
* **Why It Is Included**: Higher pain levels or persistent symptoms sometimes need prompt evaluation, even when a serious cause is less likely. The tracker cannot safely rule out uncommon conditions.
* **What Would Raise Concern**: Sudden or rapidly worsening symptoms, fainting, new weakness, confusion, severe chest or abdominal pain, trouble breathing, uncontrolled bleeding, or other major changes.

### 6. SIMPLE EXPLANATION OF THE EVIDENCE
* The estimate gives more weight to how often symptoms were logged, the average severity, the number of high-pain days, and repeated symptom combinations.
* It gives less weight to one isolated note. It cannot evaluate physical signs, medical tests, medication effects, family history, or conditions that were not entered.
* Because those missing details can change the conclusion, a licensed clinician must verify the possibilities and percentages.

### 7. DO'S
* Continue recording dates, severity, duration, triggers, meals, sleep, activity, medications, and what improved or worsened symptoms.
* Share this report with a primary-care clinician and ask which findings require examination or testing.
* Seek urgent or emergency care for severe, sudden, rapidly worsening, or life-threatening symptoms.
* Follow treatment instructions already provided by your licensed clinicians.

### 8. DON'TS
* Do not treat these possibilities as confirmed diagnoses.
* Do not start, stop, or change prescription medicine, supplements, or restrictive diets based only on this report.
* Do not ignore worsening symptoms because the major possibility has a lower percentage.
* Do not use the chatbot or report as a substitute for emergency services or an in-person medical evaluation.

### 9. QUESTIONS TO ASK YOUR CLINICIAN
* Which possible causes best match my repeated symptoms and timing?
* Are any physical examinations, laboratory tests, medication reviews, or imaging studies appropriate?
* Which warning signs should make me seek urgent or emergency care?
* What should I track next to make the pattern clearer?"""


def build_synthesis_prompt(profile_text_block, timeline_payload, statistics):
    """Creates the structured request for the clinical synthesis model."""
    objective_statistics = {
        "total_logged_days": statistics["total_days"],
        "average_pain_severity": statistics["average_severity"],
        "peak_pain_severity": statistics["peak_severity"],
        "high_severity_day_count": statistics["high_severity_count"],
        "high_severity_dates": statistics["high_severity_days"],
        "most_common_symptoms": statistics["most_common_symptoms"]
    }

    return f"""
Patient Demographic Profile:
{profile_text_block}

Objective Timeline Statistics:
{json.dumps(objective_statistics, ensure_ascii=False)}

Patient Tracked Timeline Records:
{json.dumps(timeline_payload, ensure_ascii=False)}

Create a detailed report in clear Markdown. Start with personal information and then use exactly the following sections and order:

### IMPORTANT AI SAFETY NOTICE
State that this is AI-generated educational information, not a diagnosis, and that a licensed clinician must verify it.

### 1. PERSONAL INFORMATION
List name, date of birth/age, gender, height, weight, and medical background exactly as provided. Clearly mark missing fields.

### 2. WHAT YOUR LOGS SHOW
Give objective counts, date range, average and peak severity, high-severity days, common symptoms, and repeated patterns. Do not invent weather, laboratory, medication, or lifestyle information that was not entered.

### 3. MINOR / LOWER-CONCERN POSSIBILITY — NN%
Give one plausible lower-concern possible explanation, not a confirmed diagnosis. Include: Possible Explanation, Why It May Fit, What Does Not Fit or Is Missing, and What to Discuss With a Clinician.

### 4. MEDIUM / MODERATE-CONCERN POSSIBILITY — NN%
Give one plausible moderate-concern possible explanation, not a confirmed diagnosis. Include the same four fields.

### 5. MAJOR / HIGHER-CONCERN POSSIBILITY — NN%
Give one important higher-concern condition or category that cannot be safely ruled out from self-reported data. Include the same four fields and the specific red flags that would make urgent evaluation appropriate.

The three percentages must be whole numbers that add to exactly 100. Describe them as rough, non-validated educational estimates based only on the entered data. Do not imply clinical certainty.

### 6. SIMPLE EXPLANATION OF THE EVIDENCE
Explain in ordinary language which entered facts support or weaken each possibility. Provide a concise evidence summary, not hidden chain-of-thought or private step-by-step reasoning.

### 7. DO'S
Give safe, practical tracking, clinician follow-up, and general self-care actions. Do not prescribe medication or treatment.

### 8. DON'TS
Include not changing prescriptions or supplements without a clinician, not delaying care for warning signs, and not treating AI output as a diagnosis.

### 9. QUESTIONS TO ASK YOUR CLINICIAN
Provide four focused questions based on this timeline.

Safety requirements:
- Never claim that a diagnosis is confirmed.
- Never state that a serious condition is ruled out.
- Never advise starting, stopping, or changing prescription medicine or supplements.
- Never provide an emergency reassurance based on the percentages.
- Direct the user to urgent or emergency care for severe, sudden, rapidly worsening, or life-threatening symptoms.
- Use simple language that a regular patient can understand.
"""


def validate_synthesis_result(synthesis_result):
    """Confirms that model output contains the required safe structure and probability total."""
    if not isinstance(synthesis_result, str) or not synthesis_result.strip():
        return False, "The model returned an empty report."

    required_headings = [
        "PERSONAL INFORMATION",
        "WHAT YOUR LOGS SHOW",
        "MINOR / LOWER-CONCERN POSSIBILITY",
        "MEDIUM / MODERATE-CONCERN POSSIBILITY",
        "MAJOR / HIGHER-CONCERN POSSIBILITY",
        "SIMPLE EXPLANATION OF THE EVIDENCE",
        "DO'S",
        "DON'TS",
        "QUESTIONS TO ASK YOUR CLINICIAN"
    ]

    normalized_result = synthesis_result.upper()
    missing_headings = [
        heading
        for heading in required_headings
        if heading not in normalized_result
    ]
    if missing_headings:
        return False, f"Missing required report sections: {', '.join(missing_headings)}"

    probability_matches = re.findall(
        r"POSSIBILITY\s*[—–-]\s*(\d{1,3})%",
        synthesis_result,
        flags=re.IGNORECASE
    )
    if len(probability_matches) < 3:
        return False, "The report did not include all three required percentages."

    probabilities = [int(value) for value in probability_matches[:3]]
    if any(value < 0 or value > 100 for value in probabilities):
        return False, "One or more percentages were outside the allowed range."

    if sum(probabilities) != 100:
        return False, f"The three percentages totaled {sum(probabilities)} instead of 100."

    unsafe_certainty_phrases = [
        "you definitely have",
        "this confirms that you have",
        "this rules out",
        "no need to see a doctor"
    ]
    lower_result = synthesis_result.lower()
    if any(phrase in lower_result for phrase in unsafe_certainty_phrases):
        return False, "The report used medically unsafe certainty language."

    return True, ""


def create_groq_client():
    """Returns a configured Groq client and safely reports dependency initialization failures."""
    groq_api_key = os.environ.get("GROQ_API_KEY", "")
    if not groq_api_key:
        return None, "GROQ_API_KEY is not configured."

    try:
        return Groq(api_key=groq_api_key), ""
    except TypeError as client_error:
        error_text = str(client_error)
        if "proxies" in error_text:
            return None, (
                "Groq client initialization failed because the installed HTTPX version is incompatible. "
                "Install the pinned requirements, including httpx==0.27.2."
            )
        return None, f"Groq client initialization failed: {error_text}"
    except Exception as client_error:
        return None, f"Groq client initialization failed: {str(client_error)}"


@app.route('/api/synthesize', methods=['POST'])
def synthesize_brief():
    """Generates a patient-facing educational brief from profile and timeline data."""
    try:
        payload = request.get_json(silent=True) or {}
        timeline_logs = payload.get('logs', {})
        user_profile = payload.get('profile', {})

        if not isinstance(timeline_logs, dict) or not timeline_logs:
            return jsonify({
                "error": "No timeline logs were provided. Please add entries to your calendar first."
            }), 400

        profile = normalize_profile(user_profile)
        profile_text_block = build_profile_text_block(profile)
        timeline_payload = build_timeline_payload(timeline_logs)
        statistics = calculate_timeline_statistics(timeline_payload)
        recommended_docs = determine_recommended_doctors(timeline_logs)

        engine_used = f"groq/{GROQ_MODEL}"
        client, client_initialization_warning = create_groq_client()

        if client_initialization_warning:
            print(f"Groq client warning/fallback: {client_initialization_warning}")

        if client:
            try:
                system_prompt = (
                    "You are a cautious Clinical AI Medical Education Assistant. Convert self-reported profile and symptom "
                    "timeline data into a clear patient-facing report. You may offer possible explanations and rough educational "
                    "likelihood estimates, but you must never present them as diagnoses or validated clinical probabilities. "
                    "Use only the supplied data, explicitly identify missing evidence, and prioritize medical safety."
                )

                user_prompt = build_synthesis_prompt(
                    profile_text_block,
                    timeline_payload,
                    statistics
                )

                chat_completion = client.chat.completions.create(
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt}
                    ],
                    model=GROQ_MODEL,
                    temperature=0.2,
                    max_tokens=2200
                )

                synthesis_result = chat_completion.choices[0].message.content
                is_valid_result, validation_error = validate_synthesis_result(synthesis_result)
                if not is_valid_result:
                    print(f"Groq report validation warning/fallback: {validation_error}")
                    engine_used = "fallback-algorithmic-engine"
                    synthesis_result = generate_fallback_synthesis(profile, statistics)
            except Exception as groq_err:
                print(f"Groq API call warning/fallback: {groq_err}")
                engine_used = "fallback-algorithmic-engine"
                synthesis_result = generate_fallback_synthesis(profile, statistics)
        else:
            engine_used = "fallback-algorithmic-engine"
            synthesis_result = generate_fallback_synthesis(profile, statistics)

        return jsonify({
            "status": "success",
            "brief": synthesis_result,
            "engine": engine_used,
            "disclaimer": AI_MEDICAL_DISCLAIMER,
            "recommended_doctors": recommended_docs,
            "metrics": {
                "total_days": statistics["total_days"],
                "average_severity": statistics["average_severity"],
                "peak_severity": statistics["peak_severity"],
                "high_severity_count": statistics["high_severity_count"]
            }
        })

    except Exception as runtime_error:
        return jsonify({
            "error": f"Internal Processing Error: {str(runtime_error)}"
        }), 500


def sanitize_chat_history(raw_history):
    """Normalizes a small amount of prior chat context for the follow-up endpoint."""
    if not isinstance(raw_history, list):
        return []

    clean_history = []
    for message in raw_history[-8:]:
        if not isinstance(message, dict):
            continue

        role = message.get("role")
        if role not in {"user", "assistant"}:
            continue

        content = safe_text(message.get("content"), default="", max_length=2500)
        if content:
            clean_history.append({
                "role": role,
                "content": content
            })

    return clean_history


def extract_brief_section(current_brief, heading_keywords, max_length=1800):
    """Extracts a relevant Markdown section from the generated report for fallback chat answers."""
    if not current_brief:
        return ""

    lines = str(current_brief).splitlines()
    start_index = None

    for index, line in enumerate(lines):
        normalized = line.lower()
        if line.lstrip().startswith('#') and any(keyword in normalized for keyword in heading_keywords):
            start_index = index
            break

    if start_index is None:
        return ""

    collected = []
    for line in lines[start_index:start_index + 30]:
        if collected and line.lstrip().startswith('#'):
            break
        collected.append(line)

    section = "\n".join(collected).strip()
    return section[:max_length]


def clean_markdown_for_chat(value, max_length=1200):
    """Converts a small report excerpt into readable plain text for deterministic chat replies."""
    text = safe_text(value, default="", max_length=max_length * 2)
    if not text:
        return ""

    text = re.sub(r'^#{1,6}\s*', '', text, flags=re.MULTILINE)
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'^\s*[-*]\s+', '• ', text, flags=re.MULTILINE)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()[:max_length]


def find_relevant_timeline_entries(question, timeline_payload, limit=4):
    """Finds timeline entries whose symptoms or notes overlap with words in the current question."""
    ignored_words = {
        'about', 'after', 'again', 'also', 'because', 'before', 'brief', 'could', 'does',
        'from', 'have', 'help', 'into', 'just', 'likely', 'more', 'should', 'that', 'their',
        'there', 'these', 'they', 'this', 'what', 'when', 'where', 'which', 'with', 'would',
        'your', 'explain', 'please', 'tell', 'mean', 'means'
    }
    question_terms = {
        token
        for token in re.findall(r"[a-z0-9']+", question.lower())
        if len(token) >= 4 and token not in ignored_words
    }

    scored_entries = []
    for entry in timeline_payload:
        searchable_parts = [
            entry.get('date', ''),
            ' '.join(entry.get('symptoms_reported', [])),
            entry.get('patient_notes', '')
        ]
        searchable = ' '.join(searchable_parts).lower()
        score = sum(1 for term in question_terms if term in searchable)
        if score:
            scored_entries.append((score, entry))

    scored_entries.sort(
        key=lambda item: (
            item[0],
            item[1].get('pain_severity_scale_1_to_10', 0),
            item[1].get('date', '')
        ),
        reverse=True
    )
    return [entry for _, entry in scored_entries[:limit]]


def format_relevant_entries(entries):
    """Formats matched timeline records into a compact conversational explanation."""
    if not entries:
        return ""

    formatted = []
    for entry in entries:
        symptoms = ', '.join(entry.get('symptoms_reported', [])) or 'no named symptom selected'
        note = entry.get('patient_notes', '').strip()
        note_text = f" Notes: {note}" if note else ""
        formatted.append(
            f"• {entry.get('date', 'Unknown date')}: pain {entry.get('pain_severity_scale_1_to_10', 0)}/10; "
            f"{symptoms}.{note_text}"
        )

    return "\n".join(formatted)


def resolve_conversation_subject(question, chat_history):
    """Uses recent user messages to clarify very short follow-up questions such as 'why?' or 'what about that?'"""
    normalized = question.strip().lower()
    short_follow_up_terms = {
        'why', 'why?', 'how', 'how?', 'what about that', 'explain more', 'tell me more',
        'what does that mean', 'is that serious', 'is it serious', 'what should i do'
    }

    if normalized not in short_follow_up_terms and len(normalized.split()) > 5:
        return question

    for message in reversed(chat_history):
        if message.get('role') != 'user':
            continue
        previous = safe_text(message.get('content'), default='', max_length=800)
        if previous and previous.strip().lower() != normalized:
            return f"Previous user topic: {previous}\nCurrent follow-up: {question}"

    return question


def generate_fallback_chat_response(
    question,
    profile,
    statistics,
    timeline_payload,
    current_brief,
    chat_history
):
    """Returns a question-specific deterministic response when the language model is unavailable."""
    conversational_question = resolve_conversation_subject(question, chat_history)
    normalized_question = conversational_question.lower()
    symptom_frequency = format_symptom_frequency(statistics)
    relevant_entries = find_relevant_timeline_entries(conversational_question, timeline_payload)
    relevant_entry_text = format_relevant_entries(relevant_entries)

    if any(term in normalized_question for term in [
        'emergency', '911', 'chest pain', 'cannot breathe', 'trouble breathing', 'fainting',
        'stroke', 'one-sided weakness', 'uncontrolled bleeding', 'suicidal'
    ]):
        return (
            "I cannot determine emergency risk from this tracker. If the symptom is severe, sudden, rapidly worsening, "
            "or includes trouble breathing, chest pain, fainting, new one-sided weakness, confusion, uncontrolled bleeding, "
            "or another life-threatening change, contact emergency services now. Do not wait for this chatbot or the report."
        )

    if any(term in normalized_question for term in [
        'medicine', 'medication', 'dose', 'dosage', 'supplement', 'stop taking', 'start taking',
        'increase', 'decrease', 'side effect', 'interaction'
    ]):
        medication_section = extract_brief_section(current_brief, ['do not', "don't", 'safety'])
        extra_context = clean_markdown_for_chat(medication_section, max_length=650)
        response = (
            "I can help you organize the medication question, but I cannot safely tell you to start, stop, increase, "
            "decrease, or replace a medicine or supplement from symptom logs alone. A clinician or pharmacist needs the exact "
            "product, dose, timing, reason it was prescribed, other medicines, allergies, and the timing of your symptoms."
        )
        if extra_context:
            response += f"\n\nThe report's related safety guidance says:\n{extra_context}"
        return response

    if any(term in normalized_question for term in [
        'personal information', 'my profile', 'my age', 'birthday', 'height', 'weight', 'gender',
        'medical history', 'background'
    ]):
        return (
            f"The report used the following profile information: name {profile['full_name']}; date of birth "
            f"{profile['birthday']}; approximate age {profile['age']}; gender {profile['gender']}; height "
            f"{profile['height']}; weight {profile['weight']}; and medical background: {profile['medical_notes']}. "
            "Incorrect or missing profile details can change how the report is interpreted, so update them before generating a new brief."
        )

    if any(term in normalized_question for term in [
        'probability', 'probabilities', 'percent', 'percentage', 'likely', 'likelihood',
        'minor', 'medium', 'major', 'concern tier', 'three tiers'
    ]):
        probability_section = extract_brief_section(
            current_brief,
            ['minor /', 'medium /', 'major /', 'probability', 'possibility']
        )
        report_excerpt = clean_markdown_for_chat(probability_section, max_length=1100)
        response = (
            f"Those percentages are rough educational estimates, not tested medical probabilities. They were informed by "
            f"{statistics['total_days']} logged day(s), an average pain level of {statistics['average_severity']}/10, "
            f"a highest level of {statistics['peak_severity']}/10, {statistics['high_severity_count']} high-pain day(s), "
            f"and the repeated symptom pattern: {symptom_frequency}. The app does not have an examination, vital signs, "
            "laboratory results, imaging, or a complete clinical history, so a clinician may rank the possibilities differently."
        )
        if report_excerpt:
            response += f"\n\nThe relevant part of your report is:\n{report_excerpt}"
        return response

    if any(term in normalized_question for term in [
        "do's", 'dos ', 'what should i do', 'what can i do', 'next step', 'next steps',
        'recommend', 'help myself', 'prepare for doctor', 'ask my doctor'
    ]):
        dos_section = extract_brief_section(current_brief, ["do's", 'dos and', 'what to do', 'next steps'])
        report_excerpt = clean_markdown_for_chat(dos_section, max_length=1000)
        response = (
            "The safest next steps are to keep the timeline accurate, note when each symptom starts and stops, record triggers "
            "and relieving factors, bring the report to a licensed clinician, and write down the specific questions you want answered. "
            "Seek urgent care sooner for severe, sudden, or rapidly worsening symptoms rather than relying on the probability tiers."
        )
        if report_excerpt:
            response += f"\n\nYour report lists these related actions:\n{report_excerpt}"
        return response

    if any(term in normalized_question for term in [
        "don't", 'dont ', 'avoid', 'should not', 'not do', 'unsafe'
    ]):
        donts_section = extract_brief_section(current_brief, ["don'ts", 'do not', 'avoid'])
        report_excerpt = clean_markdown_for_chat(donts_section, max_length=1000)
        response = (
            "Do not treat the report as a confirmed diagnosis, do not use the percentages to rule out a serious problem, "
            "and do not start, stop, or change medicines or supplements based only on this chatbot. Also avoid delaying urgent "
            "evaluation when symptoms are severe, sudden, or worsening."
        )
        if report_excerpt:
            response += f"\n\nThe report's related cautions are:\n{report_excerpt}"
        return response

    if any(term in normalized_question for term in [
        'why', 'evidence', 'reason', 'based on', 'thinking', 'how did', 'explain'
    ]):
        response = (
            f"In simple terms, the report looked for repetition and intensity. You entered {statistics['total_days']} day(s) "
            f"with an average pain score of {statistics['average_severity']}/10 and {statistics['high_severity_count']} day(s) "
            f"at 7/10 or higher. The most repeated symptoms were {symptom_frequency}. Repeated symptoms can make a pattern worth "
            "discussing, but they still do not identify one definite cause."
        )
        if relevant_entry_text:
            response += f"\n\nThe entries most related to your question were:\n{relevant_entry_text}"
        return response

    if any(term in normalized_question for term in [
        'summary', 'summarize', 'main point', 'bottom line', 'in simple terms', 'short explanation'
    ]):
        return (
            f"The main point is that {profile['full_name']} recorded {statistics['total_days']} symptom day(s). "
            f"Pain averaged {statistics['average_severity']}/10, peaked at {statistics['peak_severity']}/10, and the most common "
            f"reported pattern was {symptom_frequency}. The brief organizes possible explanations into lower-, moderate-, and "
            "higher-concern tiers, but none is a confirmed diagnosis. The report is most useful as a structured starting point "
            "for a clinician conversation."
        )

    if any(term in normalized_question for term in [
        'which doctor', 'what doctor', 'specialist', 'primary care', 'pcp', 'appointment'
    ]):
        doctor_section = extract_brief_section(current_brief, ['clinician', 'doctor', 'specialist'])
        report_excerpt = clean_markdown_for_chat(doctor_section, max_length=750)
        response = (
            "A primary-care clinician is usually the safest first place to review a mixed symptom timeline because they can "
            "check vital signs, perform an examination, review medicines, order initial tests, and decide whether a specialist is needed. "
            "A more urgent setting is appropriate when symptoms are severe, sudden, or rapidly worsening."
        )
        if report_excerpt:
            response += f"\n\nThe report also says:\n{report_excerpt}"
        return response

    if relevant_entry_text:
        return (
            f"I found calendar entries that appear related to your question:\n{relevant_entry_text}\n\n"
            "These entries show timing, symptom labels, notes, and pain intensity, but they cannot confirm why the symptom happened. "
            "A useful clinician question would be: ‘Could these repeated dates, triggers, and associated symptoms point to a pattern, "
            "and what examination or testing would distinguish the main possibilities?’"
        )

    brief_overview = clean_markdown_for_chat(current_brief, max_length=700)
    response = (
        f"I understand your question as: “{question}” Based on the recorded information for {profile['full_name']}, the relevant "
        f"overall pattern is {symptom_frequency}, across {statistics['total_days']} logged day(s), with average pain "
        f"{statistics['average_severity']}/10. I cannot confirm a cause from those entries, but I can explain a specific report tier, "
        "date, symptom, probability, do/don't item, or help turn your concern into a question for a clinician."
    )
    if brief_overview:
        response += f"\n\nReport context:\n{brief_overview}"
    return response


@app.route('/api/chat', methods=['POST'])
def chat_about_brief():
    """Answers follow-up questions using the generated brief and the same recorded timeline."""
    try:
        payload = request.get_json(silent=True) or {}
        question = safe_text(payload.get("question"), default="", max_length=2000)
        timeline_logs = payload.get("logs", {})
        user_profile = payload.get("profile", {})
        current_brief = safe_text(payload.get("brief"), default="No brief was supplied.", max_length=16000)
        chat_history = sanitize_chat_history(payload.get("history", []))

        if not question:
            return jsonify({"error": "Please enter a follow-up question."}), 400

        if not isinstance(timeline_logs, dict) or not timeline_logs:
            return jsonify({
                "error": "No symptom timeline is available for this follow-up question."
            }), 400

        profile = normalize_profile(user_profile)
        timeline_payload = build_timeline_payload(timeline_logs)
        statistics = calculate_timeline_statistics(timeline_payload)
        client = create_groq_client()
        engine_used = f"groq/{GROQ_MODEL}"

        if client:
            try:
                system_prompt = (
                    "You are the follow-up assistant for an AI symptom-tracking report. Answer in simple, compassionate language "
                    "using only the supplied profile, logs, generated report, and conversation. Explain evidence briefly without "
                    "revealing hidden chain-of-thought. Never confirm a diagnosis, never state that a serious condition is ruled out, "
                    "and never recommend starting, stopping, or changing medication or supplements. For severe, sudden, rapidly "
                    "worsening, or life-threatening symptoms, tell the user to seek urgent or emergency care. Clearly distinguish "
                    "general education from clinician-specific advice."
                )

                context_message = (
                    f"Patient profile:\n{build_profile_text_block(profile)}\n\n"
                    f"Objective statistics:\n{json.dumps({
                        'total_days': statistics['total_days'],
                        'average_severity': statistics['average_severity'],
                        'peak_severity': statistics['peak_severity'],
                        'high_severity_count': statistics['high_severity_count'],
                        'common_symptoms': statistics['most_common_symptoms']
                    }, ensure_ascii=False)}\n\n"
                    f"Timeline records:\n{json.dumps(timeline_payload, ensure_ascii=False)}\n\n"
                    f"Current AI report:\n{current_brief}"
                )

                messages = [
                    {"role": "system", "content": system_prompt},
                    {"role": "system", "content": context_message}
                ]
                messages.extend(chat_history)
                messages.append({"role": "user", "content": question})

                chat_completion = client.chat.completions.create(
                    messages=messages,
                    model=GROQ_MODEL,
                    temperature=0.25,
                    max_tokens=900
                )

                answer = chat_completion.choices[0].message.content
            except Exception as groq_err:
                print(f"Groq chat API warning/fallback: {groq_err}")
                engine_used = "fallback-algorithmic-engine"
                answer = generate_fallback_chat_response(
                    question,
                    profile,
                    statistics,
                    timeline_payload,
                    current_brief,
                    chat_history
                )
        else:
            engine_used = "fallback-algorithmic-engine"
            answer = generate_fallback_chat_response(
                    question,
                    profile,
                    statistics,
                    timeline_payload,
                    current_brief,
                    chat_history
                )

        return jsonify({
            "status": "success",
            "answer": answer,
            "engine": engine_used,
            "disclaimer": AI_MEDICAL_DISCLAIMER
        })

    except Exception as runtime_error:
        return jsonify({
            "error": f"Internal Processing Error: {str(runtime_error)}"
        }), 500


@app.route('/api/health', methods=['GET'])
def health_check():
    """Validates operational server edge configurations."""
    return jsonify({
        "status": "healthy",
        "environment": "US-Standard",
        "active_inference_engine": f"groq/{GROQ_MODEL}",
        "auth_provider": "Supabase" if supabase_client else "Unconfigured",
        "features": {
            "structured_health_brief": True,
            "follow_up_chat": True,
            "client_pdf_export": True,
            "mandatory_ai_disclaimer": True
        }
    })


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)
